imie_jobeet_homepage:
    pattern:  /
    defaults: { _controller: imieJobeetBundle:Job:index }

imie_jobeet_imie_job:
    resource: "@imieJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /imie_job

imieJobeetBundle_job:
        resource: "@imieJobeetBundle/Resources/config/routing/job.yml"
        prefix:   /job

imieJobeetBundle_category:
        pattern: /category/{slug}
        defaults: {_controller: imieJobeetBundle:Category:show }