imie_job:
    path:     /
    defaults: { _controller: "imieJobeetBundle:Job:index" }

imie_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "imieJobeetBundle:Job:show" }
    requirements:
        id:  \d+

# imie_job_show:
#     pattern:  /{company}/{location}/{id}/{position}
#     defaults: { _controller: "imieJobeetBundle:Job:show" }

# imie_job_show:
#     path:     /{id}/show
#     defaults: { _controller: "imieJobeetBundle:Job:show" }

imie_job_new:
    path:     /new
    defaults: { _controller: "imieJobeetBundle:Job:new" }

imie_job_create:
    path:     /create
    defaults: { _controller: "imieJobeetBundle:Job:create" }
    requirements: { _method: post }

imie_job_edit:
    path:     /{id}/edit
    defaults: { _controller: "imieJobeetBundle:Job:edit" }

imie_job_update:
    path:     /{id}/update
    defaults: { _controller: "imieJobeetBundle:Job:update" }
    requirements: { _method: post|put }

imie_job_delete:
    path:     /{id}/delete
    defaults: { _controller: "imieJobeetBundle:Job:delete" }
    requirements: { _method: post|delete }
