imie_jobeet:
    resource: "@imieJobeetBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

imieJobeetBundle_category:
    pattern:  /category/{slug}
    defaults: { _controller: imieJobeetBundle:Category:show }